# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kgrid_cpp <- function(gridmax, numpts) {
    .Call(`_condregR_kgrid_cpp`, gridmax, numpts)
}

condreg_cpp <- function(data_in, kmax) {
    .Call(`_condregR_condreg_cpp`, data_in, kmax)
}

select_kmax_cpp <- function(X, k, folds = 0L) {
    .Call(`_condregR_select_kmax_cpp`, X, k, folds)
}

select_condreg_cpp <- function(X, k, folds = 0L) {
    .Call(`_condregR_select_condreg_cpp`, X, k, folds)
}

pfweights_cpp <- function(sigma) {
    .Call(`_condregR_pfweights_cpp`, sigma)
}

transcost_cpp <- function(wnew, wold, lastearnings, reltc, wealth) {
    .Call(`_condregR_transcost_cpp`, wnew, wold, lastearnings, reltc, wealth)
}

